name: GUIHelper
version: ${project.version}
main: me.gabytm.guihelper.GUIHelper
authors: [GabyTM]
website: https://gabytm.me/
api-version: 1.13
commands:
  ghcreate:
    description: The main command
    usage: "/ghcreate [type] (argument)"
  ghhelp:
    description: List the available commands
    usage: "/ghhelp"
  ghlist:
    description: List the available types
    usage: "/ghlist"
permissions:
  guihelper.use:
    description: The permission required to access GUI Helper commands
    default: op