name: GUIHelper
version: ${project.version}
main: me.gabytm.guihelper.GUIHelper
authors: [GabyTM]
website: https://gabytm.me/
api-version: 1.14
commands:
  ghcreate:
    description: The main command
    usage: "/ghcreate [type] (argument)"
permissions:
  guihelper.use:
    description: The permission required to access GUI Helper commands
    default: op