name: GUIHelper
version: 1.0
main: me.gabytm.guihelper.GUIHelper
authors: [GabyTM]
website: https://gabytm.me/
commands:
  ghcreate:
    description: aadsad
    usage: ""
permissions:
  guihelper.use:
    description: The permission required to access GUI Helper commands
    default: op